config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'productos' => 'products#index', as: :products

  get 'producto/:id' => 'products#show', as: :product
  put 'producto/:id/update_stock_status' => 'products#update_stock_status', as: :product_update_stock

  get '/mi-cuenta' => 'customer_panel#panel', as: :customer_panel
  get '/panel-proveedor' => 'supplier_panel#panel', as: :supplier_panel

  get 'order_products_index' => 'orders#products_index', as: :order_products_index

  root 'start#home'

  devise_for :customers, :controllers => {registrations: 'customers/registrations', confirmations: 'customers/confirmations'}
  devise_for :suppliers, :controllers => { registrations: 'suppliers/registrations', sessions: 'suppliers/sessions' }

  resources :orders, only: [:new, :create, :destroy]

  get 'ipn' => 'orders#ipn'
  post 'ipn' => 'orders#ipn'

  get 'contacto' => 'start#contacto'
  get 'faq' => 'start#faq'

  mount Coupons::Engine => '/', as: 'coupons_engine'

end

app/controllers/supplier_panel_controller.rb
class SupplierPanelController < ApplicationController
  before_filter :authenticate_supplier!
  before_filter :set_supplier

  layout "suppliers"

  def panel
    @filterrific = initialize_filterrific(
        @products,
        params[:filterrific],
        persistence_id: false,
        select_options: {
            with_brand_id: Brand.options_for_select,
            with_pet_id: Pet.options_for_select
        }
    ) or return
    @products = @filterrific.find.page(params[:page]).order('priority ASC, name DESC').per(100)

    respond_to do |format|
      format.html
      format.js
      format.ajax { render :partial => "list" }
    end

  rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return
  end

  def index
  end

  private
  def set_supplier
    @supplier = current_supplier
    @products = current_supplier.products
  end
end

app/views/supplier_panel/_product.html.erb
<tr>
  <td>
      <img src="<%= product.photo.url %>" alt="Product Image" class="ui mini image">
  </td>
  <td><%= product.weight %> KG</td>
  <td><%= product.name %></td>
  <td>
      <%= best_in_place product,
                        :in_stock,
                        as: :checkbox,
                        collection: {false: "<i class='big red close icon'></i>NO".html_safe, true: "<i class='big green checkmark icon'></i>SI".html_safe},
                        url: product_update_stock_path(product.id)
      %>
  </td>
</tr>

app/views/supplier_panel/_products_table.html.erb
<table class="ui compact celled striped table">
  <thead>
  <tr>
    <th>Foto</th>
    <th>Peso</th>
    <th>Nombre</th>
    <th>En stock?</th>
  </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
      <%= render partial: 'product', locals: {product: product} %>
  <% end %>
  </tbody>
</table>

app/views/supplier_panel/panel.html.erb
<div class="ui container stackable grid">
  <div class="divider"></div>
  <div class="row">
    <div class="ui center aligned eight wide column">
      <div class="ui segments">
        <div class="ui brown inverted segment">
          <h1 class="ui header">MIS DATOS</h1>
        </div>
        <div class="ui segment">
          <h2 class="ui header"><%= @supplier.name %></h2>
        </div>
        <div class="ui segment">
          <h3><i class="icon envelope"></i> <%= @supplier.email %></h3>
          <h3><i class="icon phone"></i> <%= @supplier.phone %></h3>
        </div>
        <div class="ui segment">
          <div class="ui horizontal bulleted link list">
            <%= link_to "CERRAR SESION", destroy_supplier_session_path, method: :delete, class: 'item' %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="ui divider"></div>

  <%= render partial: 'products_table' %>

  <div class="ui divider"></div>
  <div class="ui divider"></div>


</div>