config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'productos' => 'products#index', as: :products

  get 'producto/:id' => 'products#show', as: :product
  put 'producto/:id/update_stock_status' => 'products#update_stock_status', as: :product_update_stock

  get '/mi-cuenta' => 'customer_panel#panel', as: :customer_panel
  get '/panel-proveedor' => 'supplier_panel#panel', as: :supplier_panel

  get 'order_products_index' => 'orders#products_index', as: :order_products_index

  root 'start#home'

  devise_for :customers, :controllers => {registrations: 'customers/registrations', confirmations: 'customers/confirmations'}
  devise_for :suppliers, :controllers => { registrations: 'suppliers/registrations', sessions: 'suppliers/sessions' }

  resources :orders, only: [:new, :create, :destroy]

  get 'ipn' => 'orders#ipn'
  post 'ipn' => 'orders#ipn'

  get 'contacto' => 'start#contacto'
  get 'faq' => 'start#faq'

  mount Coupons::Engine => '/', as: 'coupons_engine'

end

app/controllers/start_controller.rb
class StartController < ApplicationController
  def home
  end

  def faq
  end

  def contacto
  end
  
end

app/helpers/start_helper.rb
module StartHelper
end

app/views/start/_instructions_md_semantic.html.erb
<div class="ui container fluid">
  <div class="banner-principal">
    <h1 class="instruction-title">
      QUE EL ALIMENTO DE TUS MASCOTAS YA NO SEA UN PROBLEMA
    </h1>
    <%= image_tag 'banner-principal.png', class: 'ui centered image' %>
  </div>
</div>

<div class="ui container fluid">
  <div class="ui center aligned grid">
    <div class="ui row white-background">
      <div class="sixteen wide column">
        <h1 class="instruction-title no-margin">
          ¿CÓMO FUNCIONA CLUB DE HUELLAS?
        </h1>
      </div>
    </div>


    <div class="instruction custom-yellow row middle aligned">
      <div class="ui container center aligned middle aligned grid">
        <div class="six wide column">
          <div class="instruction-image">
            <%= image_tag 'icono-registrarme.png', class: 'ui centered image' %>
          </div>
        </div>
        <div class="ten wide column">
          <div class="content">
            <div class="number-circle vertical-align">
              <h1>1</h1>
            </div>
            <h1 class="instruction-title">REGISTRATE EN LA WEB</h1>
            <p>REGISTRARTE ES SÚPER FÁCIL, UNICAMENTE TENÉS QUE LLENAR EL FORMULARIO
              CON TU NOMBRE, EMAIL Y NÚMERO DE TELÉFONO. <br>
              PODÉS HACERLO DESDE TU CELULAR O COMPUTADORA.</p>
          </div>
        </div>
      </div>
    </div>

    <div class="instruction light-yellow row middle aligned">
      <div class="ui container center aligned middle aligned grid">
      <div class="ten wide column">
        <div class="content">
          <div class="number-circle vertical-align">
            <h1>2</h1>
          </div>
          <h1 class="instruction-title">SELECCIONA LOS PRODUCTOS</h1>
          <p>ELEGÍ LOS PRODUCTOS QUE CONSUMEN TUS MASCOTAS, TENEMOS DE TODAS
            LAS MARCAS, VARIEDADES Y TAMAÑOS.</p>
        </div>
      </div>
      <div class="six wide column">
        <div class="instruction-image">
          <%= image_tag 'icono-comida.png', class: 'ui centered image' %>
        </div>
      </div>
      </div>
    </div>

    <div class="instruction custom-yellow row middle aligned">
      <div class="ui container center aligned middle aligned grid">
      <div class="six wide column">
        <div class="instruction-image">
          <%= image_tag 'icono-tarjeta.png', class: 'ui centered image' %>
        </div>
      </div>
      <div class="ten wide column">
        <div class="content">
          <div class="number-circle vertical-align">
            <h1>3</h1>
          </div>
          <h1 class="instruction-title">ELEGÍ COMO QUERÉS PAGAR</h1>
          <p>
            PODÉS PAGAR EN EFECTIVO AL MOMENTO DE LA ENTREGA, O EN CUOTAS
            CON TU TARJETA DE CRÉDITO A TRAVÉS DE MERCADOPAGO.
          </p>
        </div>
      </div>
      </div>
    </div>


    <div class="light-yellow middle aligned row">
      <div class="ui container center aligned middle aligned grid">
      <div class="five wide column">
        <%= image_tag 'perrito-1.png', class: 'ui centered image' %>
      </div>
      <div class="six wide column">
        <div class="content">
          <h1 class="finishing-title">¡LISTO!</h1>
          <h1 class="finishing-sentence">
            Nosotros nos encargamos de llevarte
            el alimento a tu domicilio.
          </h1>
        </div>
      </div>
      <div class="five wide column">
        <%= image_tag 'perrito-2.png', class: 'ui centered image' %>
      </div>
      </div>
    </div>


    <div class="row">
        <div class="sixteen wide column">
          <div class="content">
            <div class="divider"></div>
            <h1 class="instruction-title">¿QUE ESPERÁS PARA UNIRTE AL CLUB?</h1>
            <%= link_to new_customer_registration_path do %>
                <%= image_tag 'boton-suscripcion.png', class: 'ui centered image' %>
            <% end %>
          </div>
        </div>
    </div>

  </div>
</div>

app/views/start/_instructions_xs_semantic.html.erb
<div class="ui container fluid">
  <div class="ui center aligned grid">
    <div class="row">
      <div class="banner-principal">
        <h1 class="instruction-title-xs">
          QUE EL ALIMENTO DE TUS MASCOTAS YA NO SEA UN PROBLEMA
        </h1>
        <%= image_tag 'banner-principal-xs.png', class: 'ui image' %>
      </div>
    </div>

    <div class="row white-background">
      <div class="sixteen wide column">
        <h1 class="instruction-title-xs">
          ¿CÓMO FUNCIONA CLUB DE HUELLAS?
        </h1>
      </div>
    </div>

    <div class="row custom-yellow">
      <div class="sixteen wide column">
        <div class="instruction-image">
          <%= image_tag 'icono-registrarme.png', class: 'ui centered medium image' %>
        </div>
      </div>
      <div class="sixteen wide column">
        <div class="content-xs">
          <h1 class="instruction-title-xs">REGISTRATE EN LA WEB</h1>
          <p>REGISTRARTE ES SÚPER FÁCIL, UNICAMENTE TENÉS QUE LLENAR EL FORMULARIO
            CON TU NOMBRE, EMAIL Y NÚMERO DE TELÉFONO.</p>
        </div>
      </div>
    </div>

    <div class="row light-yellow">
      <div class="sixteen wide column">
        <div class="instruction-image">
          <%= image_tag 'icono-comida.png', class: 'ui centered medium image' %>
        </div>
      </div>
      <div class="sixteen wide column">
        <div class="content-xs">
          <h1 class="instruction-title-xs">SELECCIONA LOS PRODUCTOS</h1>
          <p>ELEGÍ LOS PRODUCTOS QUE CONSUMEN TUS MASCOTAS, TENEMOS DE TODAS
            LAS MARCAS, VARIEDADES Y TAMAÑOS.</p>
        </div>
      </div>
    </div>

    <div class="row custom-yellow">
      <div class="sixteen wide column">
        <div class="instruction-image">
          <%= image_tag 'icono-tarjeta.png', class: 'ui centered medium image' %>
        </div>
      </div>
      <div class="sixteen wide column">
        <div class="content-xs">
          <h1 class="instruction-title-xs">ELEGÍ COMO QUERÉS PAGAR</h1>
          <p>
            PODÉS PAGAR EN EFECTIVO AL MOMENTO DE LA ENTREGA, O EN CUOTAS
            CON TU TARJETA DE CRÉDITO A TRAVÉS DE MERCADOPAGO.
          </p>
        </div>
      </div>
    </div>

    <div class="light-yellow row">
      <div class="sixteen wide column">
        <div class="content">
          <h1 class="finishing-title-xs">¡LISTO!</h1>
          <h1 class="finishing-sentence-xs">
            Nosotros nos encargamos de llevarte
            el alimento a tu domicilio.
          </h1>
        </div>
      </div>
      <div class="sixteen wide column">
        <%= image_tag 'perrito-2.png', class: 'ui centered image' %>
      </div>
      <div class="sixteen wide column">
        <%= image_tag 'perrito-1.png', class: 'ui centered image' %>
      </div>
      <div class="sixteen wide column">
        <div class="content">
          <div class="divider"></div>
          <h1 class="instruction-title-xs">¿QUE ESPERÁS PARA UNIRTE AL CLUB?</h1>
          <%= link_to new_customer_registration_path do %>
              <%= image_tag 'boton-suscripcion.png', class: 'ui centered image' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/start/contacto.html.erb
<div class="ui container center aligned grid">
  <div class="row">
    <div class="sixteen wide column">
      <div class="divider"></div>
      <%= image_tag 'whatsapp-logo.png' %>
      <h2>+ (351) 5122959 </h2>
      <div class="divider"></div>
      <i class="icon huge envelope"></i>
      <a href="mailto:contacto@clubdehuellas.com" style="color: #333">
        <h2>contacto@clubdehuellas.com</h2>
      </a>
      <div class="divider"></div>
    </div>
  </div>
</div>

app/views/start/faq.html.erb
<div class="ui container two column stackable grid">
  <div class="divider"></div>
  <div class="centered column">
    <h2>¿En que localidad funciona Club de Huellas?</h2>
    <p>
      Por el momento funcionamos en la Ciudad de Córdoba, incluidos Villa Allende y Arguello.
      Tené en cuenta que en Villa Allende y alrededores entregamos solo los días Miércoles.
    </p>
    <h2>¿Cuanto cuesta el envío?</h2>
    <p>
      El envío es GRATUITO para toda la Ciudad de Córdoba. Para Villa Allende y Arguello tiene un recargo de $30
    </p>
  </div>
  <div class="divider"></div>
  <div class="divider"></div>
  <div class="divider"></div><div class="divider"></div><div class="divider"></div>
  <div class="divider"></div>
  <div class="divider"></div>
  <div class="divider"></div>
  <div class="divider"></div>
  <div class="divider"></div>
  <div class="divider"></div>
</div>

app/views/start/home.html.erb
<div class="ui one column grid">
  <div class="computer tablet only column">
    <%= render partial: 'instructions_md_semantic' %>
  </div>

  <div class="mobile only column">
    <%= render partial: 'instructions_xs_semantic' %>
  </div>
</div>