config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'productos' => 'products#index', as: :products

  get 'producto/:id' => 'products#show', as: :product
  put 'producto/:id/update_stock_status' => 'products#update_stock_status', as: :product_update_stock

  get '/mi-cuenta' => 'customer_panel#panel', as: :customer_panel
  get '/panel-proveedor' => 'supplier_panel#panel', as: :supplier_panel

  get 'order_products_index' => 'orders#products_index', as: :order_products_index

  root 'start#home'

  devise_for :customers, :controllers => {registrations: 'customers/registrations', confirmations: 'customers/confirmations'}
  devise_for :suppliers, :controllers => { registrations: 'suppliers/registrations', sessions: 'suppliers/sessions' }

  resources :orders, only: [:new, :create, :destroy]

  get 'ipn' => 'orders#ipn'
  post 'ipn' => 'orders#ipn'

  get 'contacto' => 'start#contacto'
  get 'faq' => 'start#faq'

  mount Coupons::Engine => '/', as: 'coupons_engine'

end

app/views/shared/_facebook_pixel.html.erb
<!-- Facebook Pixel Code -->
<script>
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '1544774298867581', {
        em: 'insert_email_variable,'
    });
    fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
               src="https://www.facebook.com/tr?id=1544774298867581&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->

app/views/shared/_footer.html.erb
<footer>
  <div class="ui container fluid" style="margin: 0 !important;">

    <div class="ui inverted custom-brown segment center aligned">
      <div class="ui stackable three columns grid">
        <div class="center aligned column">
          <%= link_to "http://movipaq.com" do %>
              Toda nuestra logistica es llevada a cabo por:
              <%= image_tag 'movipaq.png', class: 'ui medium centered image' %>
              www.movipaq.com
          <% end %>
        </div>
        <div class="center aligned column">
          <h2 class="footer-header">SEGUINOS EN:</h2>
          <%= link_to facebook_url, class: 'footer-social-icon' do %>
              <%= image_tag 'Facebook.png' %>
          <% end %>

          <%= link_to instagram_url, class: 'footer-social-icon' do %>
              <%= image_tag 'Instgram.png' %>
          <% end %>

          <a href="mailto:contacto@clubdehuellas.com">
            <h4>contacto@clubdehuellas.com</h4>
          </a>
        </div>
        <div class="center aligned column">
          <%= image_tag 'whatsapp-logo.png' %>
          <h2>+ (351) 5122959 </h2>
        </div>
      </div>
      <div class="ui hidden divider"></div>
      <div class="ui hidden divider"></div>
      <div class="ui hidden divider"></div>
      <div class="ui hidden divider"></div>
    </div>


  </div>

</footer>

app/views/shared/_header.html.erb
<header>
  <div class="ui container fluid" style="margin: 0 !important;">
    <div class="ui inverted custom-brown segment">
      <div class="ui container stackable grid">
        <div class="ui sixteen wide computer only column">
          <div class="row" style="position: absolute; width: 100%; padding-top: 20px; padding-right: 45px;">
            <% if customer_signed_in? %>
                <h1 class="ui right aligned inverted header">
                  ¡Hola <%= current_customer.nombre %>!
                </h1>
            <% end %>
          </div>
          <div class="row">
            <div class="ui stackable inverted text fluid menu" id="main-menu">
              <%= link_to root_path, class: 'item logo' do %>
                  <%= image_tag 'clubdehuellas.png' %>
              <% end %>
              <%= link_to root_path, class: current_class?(root_path) do %>
                  INICIO
              <% end %>
              <%= link_to products_path, class: current_class?(products_path) do %>
                  PRODUCTOS
              <% end %>
              <%= link_to faq_path, class: current_class?(faq_path) do %>
                  PREGUNTAS FRECUENTES
              <% end %>
              <%= link_to contacto_path, class: current_class?(contacto_path) do %>
                  CONTACTANOS
              <% end %>
              <div class="right menu">
                <% if customer_signed_in? %>

                    <%= link_to customer_panel_path, class: current_class?(customer_panel_path) do %>
                        <i class="user icon"></i>
                        MI CUENTA
                    <% end %>

                    <%= link_to new_order_path, class: 'ui green small button' do %>
                        REALIZAR UN PEDIDO
                    <% end %>


                <% else %>
                    <%= link_to new_customer_session_path, class: 'ui green small button' do %>
                        <i class="sign in icon"></i>
                        REALIZAR UN PEDIDO
                    <% end %>
                <% end %>
              </div>

            </div>
          </div>
        </div>


        <div class="ui mobile tablet only center aligned row">
          <%= link_to root_path, class: 'ui centered image logo mobile-logo' do %>
              <%= image_tag 'clubdehuellas.png' %>
          <% end %>
        </div>
        <div class="ui mobile tablet only center aligned row">
          <a class="toggle-mobile-menu ui icon inverted button">
            <i class="sidebar icon"></i>
            Menu
          </a>
        </div>
        <div class="ui mobile tablet only center aligned column">
          <% if customer_signed_in? %>
            <h1 class="ui center aligned inverted header">
              ¡Hola <%= current_customer.nombre %>!
            </h1>
          <% end %>
          <div class="ui inverted vertical text menu" style="margin: auto;">
            <% if customer_signed_in? %>

                <%= link_to customer_panel_path, class: current_class?(customer_panel_path) do %>
                    <i class="user icon"></i>
                    MI CUENTA
                <% end %>

                <%= link_to new_order_path, class: 'ui green button' do %>
                    REALIZAR UN PEDIDO
                <% end %>


            <% else %>
                <%= link_to new_customer_session_path, class: 'ui green button' do %>
                    <i class="sign in icon"></i>
                    REALIZAR UN PEDIDO
                <% end %>
            <% end %>
          </div>
        </div>


      </div>
    </div>
  </div>
</header>

app/views/shared/_menu_sidebar.html.erb
<div class="ui sidebar inverted vertical menu" id="mobile_menu_sidebar">
  <%= link_to root_path, class: current_class?(root_path) do %>
      INICIO
  <% end %>
  <%= link_to products_path, class: current_class?(products_path) do %>
      PRODUCTOS
  <% end %>
  <%= link_to faq_path, class: current_class?(faq_path) do %>
      PREGUNTAS FRECUENTES
  <% end %>
  <%= link_to contacto_path, class: current_class?(contacto_path) do %>
      CONTACTANOS
  <% end %>
  <div class="divider"></div>
  <% if customer_signed_in? %>
      <h3 class="ui black fluid big button">
        ¡Hola <%= current_customer.nombre %>!
      </h3>
      <%= link_to customer_panel_path, class: 'ui blue fluid button' do %>
          MI CUENTA
      <% end %>

      <%= link_to new_order_path, class: 'ui green fluid button' do %>
          REALIZAR UN PEDIDO
      <% end %>

  <% else %>
      <%= link_to new_customer_session_path, class: 'ui green fluid button' do %>
          REALIZAR UN PEDIDO
      <% end %>

  <% end %>
</div>