config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'productos' => 'products#index', as: :products

  get 'producto/:id' => 'products#show', as: :product
  put 'producto/:id/update_stock_status' => 'products#update_stock_status', as: :product_update_stock

  get '/mi-cuenta' => 'customer_panel#panel', as: :customer_panel
  get '/panel-proveedor' => 'supplier_panel#panel', as: :supplier_panel

  get 'order_products_index' => 'orders#products_index', as: :order_products_index

  root 'start#home'

  devise_for :customers, :controllers => {registrations: 'customers/registrations', confirmations: 'customers/confirmations'}
  devise_for :suppliers, :controllers => { registrations: 'suppliers/registrations', sessions: 'suppliers/sessions' }

  resources :orders, only: [:new, :create, :destroy]

  get 'ipn' => 'orders#ipn'
  post 'ipn' => 'orders#ipn'

  get 'contacto' => 'start#contacto'
  get 'faq' => 'start#faq'

  mount Coupons::Engine => '/', as: 'coupons_engine'

end

app/controllers/customer_panel_controller.rb
class CustomerPanelController < ApplicationController
  before_filter :authenticate_customer!
  before_filter :set_customer

  def panel
  end

  private
  def set_customer
    @customer = current_customer
  end
end

app/views/customer_panel/_order.html.erb
<div class="ui segments">
  <div class="ui blue inverted segment">
    <h2 class="ui center aligned header">
      PEDIDO Nº<%= order.id %>
    </h2>
  </div>
  <div class="ui segment">
    <div class="ui stackable padded relaxed grid">
      <div class="twelve wide column">
        <h2 class="ui header">
          <i class="marker orange icon"></i>
          <div class="content">
            DIRECCIÓN:
            <div class="sub header"><%= order.address %>, <%= order.zone.name %></div>
          </div>
        </h2>
      </div>
      <div class="four wide column">
        <h2 class="ui header">
          <% case order.status %>
          <% when 'authorized' %>
              <i class="icon checkmark green"></i>
              <div class="content">
                ESTADO:
                <div class="sub header green">RECIBIDO</div>
              </div>
          <% when 'pending' %>
              <i class="icon wait yellow"></i>
              <div class="content">
                ESTADO:
                <div class="sub header yellow">PENDIENTE DE PAGO MERCADOPAGO</div>
              </div>
          <% when 'cancelled' %>
              <i class="icon close red"></i>
              <div class="content">
                ESTADO:
                <div class="sub header red">CANCELADO</div>
              </div>
          <% else %>
          <% end %>
        </h2>
      </div>
    </div>
  </div>


  <div class="ui segment">
    <table class="ui striped padded center aligned large table subscription-table">
      <thead>
      <tr>
        <th>&nbsp;</th>
        <th>PRODUCTO</th>
        <th>PESO</th>
        <th>PRECIO</th>
        <th>CANTIDAD</th>
        <th>SUBTOTAL</th>
      </tr>
      </thead>
      <tbody id="subscription_products">
      <% order.order_items.each do |si| %>
          <tr class="product_row">
            <td class="product-img">
              <img src="<%= si.product.photo.url %>" class="ui tiny centered image">
            </td>
            <td class="product-name">
              <%= si.product.name %>
            </td>
            <td class="product-weight">
              <%= si.product.weight %> KG
            </td>
            <td class="unit-price">
              <span class="amount">$<%= si.unit_price %></span>
            </td>
            <td class="product-quantity">
              <%= si.quantity %>
            </td>
            <td class="total-price">
              <span class="amount">$<%= si.total_price %></span>
            </td>
          </tr>
      <% end %>

      <tr class="product_row">
        <td class="product-img"><%= image_tag 'clubdehuellas.png', class: 'ui tiny centered image' %></td>
        <td class="product-name">COSTO DEL SERVICIO</td>
        <td></td>
        <td></td>
        <td></td>
        <td class="total-price"><span class="amount">$<%= order.shipping_cost %></span></td>
      </tr>
      </tbody>
    </table>
  </div>

  <div class="ui segment">
    <div class="ui stackable padded relaxed grid">
      <div class="six wide column">
        <h3 class="ui header">
          <i class="money icon"></i>
          <div class="content">
            FORMA DE PAGO:
            <% if order.payment_method == 'MERCADOPAGO' %>
                <div class="sub header">TARJETA DE CRÉDITO MERCADOPAGO</div>
            <% elsif order.payment_method == 'EFECTIVO' %>
                <div class="sub header">EFECTIVO EN ENTREGA</div>
            <% end %>
          </div>
        </h3>
      </div>
      <div class="six wide column">

      </div>
      <div class="four wide center aligned column">
        <div class="ui green small statistic">
          <div class="value">
            $<%= order.total %>
          </div>
          <div class="label">
            TOTAL
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="ui segment">
    <div class="ui stackable padded relaxed grid">
      <div class="eight wide column">
        <h3 class="ui header">
          <i class="calendar icon"></i>
          <div class="content">
            FECHA DE ENTREGA:
            <div class="sub header">
              <%= l(order.delivery_date, format: :short).upcase  %>
            </div>
          </div>
        </h3>
      </div>
      <div class="eight wide right aligned column">
        <% case order.status %>
        <% when 'authorized' %>
            <%= link_to "Cancelar", order_path(order), method: :delete, class: 'ui small red button' %>
        <% when 'pending' %>
            <%= link_to "Cancelar", order_path(order), method: :delete, class: 'ui small red button' %>
        <% else %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/customer_panel/_subscription.html.erb
<div class="ui segments">
  <div class="ui blue inverted segment">
    <h2 class="ui center aligned header">
      SUSCRIPCION Nº<%= subscription.id %>
    </h2>
  </div>
  <div class="ui segment">
    <div class="ui stackable padded relaxed grid">
      <div class="twelve wide column">
        <h2 class="ui header">
          <i class="marker orange icon"></i>
          <div class="content">
            DIRECCIÓN:
            <div class="sub header"><%= subscription.address %>, <%= subscription.zone.name %></div>
          </div>
        </h2>
      </div>
      <div class="four wide column">
        <h2 class="ui header">
          <% case subscription.status %>
          <% when 'authorized' %>
              <i class="icon checkmark green"></i>
              <div class="content">
                ESTADO:
                <div class="sub header green">ACTIVA</div>
              </div>
          <% when 'pending' %>
              <i class="icon wait yellow"></i>
              <div class="content">
                ESTADO:
                <div class="sub header yellow">PENDIENTE DE APROBACIÓN MERCADOPAGO</div>
              </div>
          <% when 'paused' %>
              <i class="icon pause blue"></i>
              <div class="content">
                ESTADO:
                <div class="sub header blue">PAUSADA</div>
              </div>
          <% when 'cancelled' %>
              <i class="icon close red"></i>
              <div class="content">
                ESTADO:
                <div class="sub header red">CANCELADA</div>
              </div>
          <% else %>
          <% end %>
        </h2>
      </div>
    </div>
  </div>


  <div class="ui segment">
    <table class="ui striped padded center aligned large table subscription-table">
      <thead>
      <tr>
        <th>&nbsp;</th>
        <th>PRODUCTO</th>
        <th>PESO</th>
        <th>PRECIO</th>
        <th>CANTIDAD</th>
        <th>SUBTOTAL</th>
      </tr>
      </thead>
      <tbody id="subscription_products">
      <% subscription.subscription_items.each do |si| %>
          <tr class="product_row">
            <td class="product-img">
              <img src="<%= si.product.photo.url %>" class="ui tiny centered image">
            </td>
            <td class="product-name">
              <%= si.product.name %>
            </td>
            <td class="product-weight">
              <%= si.product.weight %> KG
            </td>
            <td class="unit-price">
              <span class="amount">$<%= si.unit_price %></span>
            </td>
            <td class="product-quantity">
              <%= si.quantity %>
            </td>
            <td class="total-price">
              <span class="amount">$<%= si.total_price %></span>
            </td>
          </tr>
      <% end %>

      <tr class="product_row">
        <td class="product-img"><%= image_tag 'clubdehuellas.png', class: 'ui tiny centered image' %></td>
        <td class="product-name">COSTO DEL SERVICIO</td>
        <td></td>
        <td></td>
        <td></td>
        <td class="total-price"><span class="amount">$<%= subscription.shipping_cost %></span></td>
      </tr>
      </tbody>
    </table>
  </div>

  <div class="ui segment">
    <div class="ui stackable padded relaxed grid">
      <div class="six wide column">
        <h3 class="ui header">
          <i class="money icon"></i>
          <div class="content">
            FORMA DE PAGO:
            <% if subscription.payment_method == 'MERCADOPAGO' %>
                <div class="sub header">DÉBITO AUTOMÁTICO MERCADOPAGO</div>
            <% elsif subscription.payment_method == 'EFECTIVO' %>
                <div class="sub header">EFECTIVO EN ENTREGA</div>
            <% end %>
          </div>
        </h3>
      </div>
      <div class="six wide column">

      </div>
      <div class="four wide center aligned column">
        <div class="ui green small statistic">
          <div class="value">
            $<%= subscription.total %>
          </div>
          <div class="label">
            TOTAL
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="ui segment">
    <div class="ui stackable padded relaxed grid">
      <div class="eight wide column">
        <h3 class="ui header">
          <i class="calendar icon"></i>
          <div class="content">
            PROXIMA ENTREGA:
            <div class="sub header">
              ENTRE <%= l(subscription.deliveries.last.start_date, format: :short).upcase  %> Y <%= l(subscription.deliveries.last.end_date, format: :short).upcase %>
            </div>
          </div>
        </h3>
      </div>
      <div class="eight wide right aligned column">
        <% case subscription.status %>
        <% when 'authorized' %>
            <%= link_to "Pausar", pause_subscription_path(subscription), class: 'ui small button' %>
            <%= link_to "Cancelar", subscription_path(subscription), method: :delete, class: 'ui small red button' %>
        <% when 'pending' %>
            <%= link_to "Cancelar", subscription_path(subscription), method: :delete, class: 'ui small red button' %>
        <% when 'paused' %>
            <%= link_to "Reactivar", reactivate_subscription_path(subscription), class: 'ui small green button' %>
            <%= link_to "Cancelar", subscription_path(subscription), method: :delete, class: 'ui small red button' %>
        <% else %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/customer_panel/panel.html.erb
<div class="ui container stackable grid">
  <div class="divider"></div>
  <div class="row">
    <div class="ui center aligned eight wide column">
      <div class="ui segments">
        <div class="ui brown inverted segment">
          <h1 class="ui header">MIS DATOS</h1>
        </div>
        <div class="ui segment">
          <h2 class="ui header"><%= @customer.nombre %></h2>
        </div>
        <div class="ui segment">
          <h3><i class="icon envelope"></i> <%= @customer.email %></h3>
          <h3><i class="icon phone"></i> <%= @customer.phone %></h3>
        </div>
        <div class="ui segment">
          <div class="ui horizontal bulleted link list">
            <%= link_to "MODIFICAR MIS DATOS", edit_customer_registration_path, class: 'item' %>
            <%= link_to "CERRAR SESION", destroy_customer_session_path, method: :delete, class: 'item' %>
          </div>
        </div>
      </div>
    </div>
    <div class="ui center aligned eight wide column">
      <div class="ui segment">
        <a href="<%= new_order_path %>">
          <div class="ui massive icon header">
            <i class="massive icon add circle green" style="font-size: 12rem;"></i>
            <h1 class="content">NUEVO PEDIDO</h1>
          </div>
        </a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="ui sixteen wide column">
      <h1 class="ui center aligned inverted block header">MIS PEDIDOS</h1>

      <% if @customer.orders.empty? %>
        <h4 class="ui center aligned header">
          No has hecho ningún pedido aún.
        </h4>
      <% end %>
      <% @customer.orders.each do |order| %>
          <%= render partial: 'order', locals: {order: order} %>
      <% end %>
    </div>
  </div>

  <div class="ui divider"></div>

</div>


<script>
  
</script>